/*
 * ============================================================
 * deepBlack Design Tokens
 *
 * AUTO-GENERATED FILE
 * Source: design/tokens/colors.json
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * ============================================================
 */

#ifndef DESIGN_TOKENS_H
#define DESIGN_TOKENS_H

/* Surface Tokens */
#define SURFACE_00           0x000000ff
#define SURFACE_01           0x050805ff
#define SURFACE_02           0x080c08ff

/* Text Tokens */
#define TEXT_PRIMARY         0xd8ffe0ff
#define TEXT_SECONDARY       0x7fa88aff
#define TEXT_MUTED           0x4d6654ff

/* Accent Tokens */
#define ACCENT_PRIMARY       0x39ff14ff
#define ACCENT_SECONDARY     0x1f7f35ff
#define ACCENT_DIAGNOSTIC    0x7cff9bff

/* State Tokens */
#define STATE_WARNING        0xffb000ff
#define STATE_CRITICAL       0xff0033ff

/* Border Tokens */
#define BORDER_INACTIVE      0x113311ff
#define BORDER_ACTIVE        ACCENT_PRIMARY
#define BORDER_CRITICAL      STATE_CRITICAL

#endif /* DESIGN_TOKENS_H */
