/*
 * ============================================================
 * deepBlack Design Tokens
 *
 * AUTO-GENERATED FILE
 * Flavor: deepblack
 * Source: profiles/flavors/deepblack.json
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * ============================================================
 */

#ifndef DESIGN_TOKENS_H
#define DESIGN_TOKENS_H

/* Surface Tokens */
#define SURFACE_00           0x000000ff
#define SURFACE_01           0x050805ff
#define SURFACE_02           0x080c08ff

/* Text Tokens */
#define TEXT_PRIMARY         0xd8ffe0ff
#define TEXT_SECONDARY       0x7fa88aff
#define TEXT_MUTED           0x4d6654ff

/* Accent Tokens */
#define ACCENT_PRIMARY       0x39ff14ff
#define ACCENT_SECONDARY     0x1f7f35ff
#define ACCENT_DIAGNOSTIC    0x7cff9bff

/* State Tokens */
#define STATE_WARNING        0xffb000ff
#define STATE_CRITICAL       0xff0033ff

/* Border Tokens */
#define BORDER_INACTIVE      0x113311ff
#define BORDER_ACTIVE        ACCENT_PRIMARY
#define BORDER_CRITICAL      STATE_CRITICAL

/* Surface Tokens */
#define SURFACE_03           0x101a12ff
#define SURFACE_04           0x17231aff

/* State Tokens */
#define STATE_SUCCESS        0x39ff14ff

/* Syntax Tokens */
#define SYNTAX_COMMENT       0x4d6654ff
#define SYNTAX_KEYWORD       0xc792eaff
#define SYNTAX_FUNCTION      0x7cff9bff
#define SYNTAX_STRING        0x8fd6a0ff
#define SYNTAX_NUMBER        0xd6b85aff
#define SYNTAX_TYPE          0x66c7d1ff
#define SYNTAX_CONSTANT      0xff9e64ff
#define SYNTAX_OPERATOR      0x9fb8a6ff
#define SYNTAX_SPECIAL       0xffd166ff
#define SYNTAX_VARIABLE      0xd8ffe0ff
#define SYNTAX_PROPERTY      0x5fbf8fff
#define SYNTAX_PARAMETER     0xb6d9bfff
#define SYNTAX_PREPROC       0xb48eadff

#endif /* DESIGN_TOKENS_H */
