#!/usr/bin/env python3
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COLORS = ROOT / "design" / "tokens" / "colors.json"
OUT_DWL = ROOT / "generated" / "dwl" / "design_tokens.h"

GROUPS = {
    "SURFACE": "Surface Tokens",
    "TEXT": "Text Tokens",
    "ACCENT": "Accent Tokens",
    "STATE": "State Tokens",
    "BORDER": "Border Tokens",
}


def group_for(name: str) -> str:
    return name.split("_", 1)[0]


def main() -> None:
    tokens = json.loads(COLORS.read_text())

    lines = [
        "/*",
        " * ============================================================",
        " * deepBlack Design Tokens",
        " *",
        " * AUTO-GENERATED FILE",
        " * Source: design/tokens/colors.json",
        " *",
        " * DO NOT EDIT THIS FILE DIRECTLY.",
        " * ============================================================",
        " */",
        "",
        "#ifndef DESIGN_TOKENS_H",
        "#define DESIGN_TOKENS_H",
        "",
    ]

    current_group = None

    for name, value in tokens.items():
        group = group_for(name)

        if group != current_group:
            if current_group is not None:
                lines.append("")
            lines.append(f"/* {GROUPS.get(group, group.title() + ' Tokens')} */")
            current_group = group

        lines.append(f"#define {name:<20} {value}")

    lines += [
        "",
        "#endif /* DESIGN_TOKENS_H */",
        "",
    ]

    OUT_DWL.parent.mkdir(parents=True, exist_ok=True)
    OUT_DWL.write_text("\n".join(lines))

    print(f"[deepBlack] generated {OUT_DWL}")


if __name__ == "__main__":
    main()
