#!/usr/bin/env python3
"""Generate deepBlack machine-specific build assets."""

from __future__ import annotations

import argparse
import json
import shlex
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
PROFILES_DIR = ROOT / "profiles" / "machines"

OUT_HEADER = ROOT / "generated" / "dwl" / "machine_profile.h"
OUT_FOOT_SIZE = ROOT / "generated" / "machine" / "foot-font-size"
OUT_GREETER = ROOT / "generated" / "greetd" / "deepblack-greeter"

MODKEYS = {
    "ALT": "WLR_MODIFIER_ALT",
    "LOGO": "WLR_MODIFIER_LOGO",
}


def c_float(value: Any) -> str:
    number = float(value)
    text = f"{number:.6g}"

    if "." not in text and "e" not in text.lower():
        text += ".0"

    return f"{text}f"


def c_string(value: Any) -> str:
    if value is None:
        return "NULL"

    if not isinstance(value, str) or not value:
        raise ValueError("monitor name must be a non-empty string or null")

    return json.dumps(value)


def load_profile(machine: str) -> dict[str, Any]:
    path = PROFILES_DIR / f"{machine}.json"

    if not path.is_file():
        available = ", ".join(sorted(p.stem for p in PROFILES_DIR.glob("*.json")))
        raise FileNotFoundError(
            f"unknown machine profile: {machine}\n"
            f"available profiles: {available or 'none'}"
        )

    profile = json.loads(path.read_text(encoding="utf-8"))

    if profile.get("id") != machine:
        raise ValueError(
            f"profile id {profile.get('id')!r} does not match filename {machine!r}"
        )

    monitors = profile.get("monitors")

    if not isinstance(monitors, list) or not monitors:
        raise ValueError("machine profile must define at least one monitor rule")

    modkey = profile.get("modkey")

    if modkey not in MODKEYS:
        raise ValueError(
            f"unsupported modkey {modkey!r}; expected one of: "
            f"{', '.join(MODKEYS)}"
        )

    font_size = profile.get("foot_font_size")

    if not isinstance(font_size, int) or not 6 <= font_size <= 32:
        raise ValueError("foot_font_size must be an integer between 6 and 32")

    if not isinstance(profile.get("natural_scrolling"), bool):
        raise ValueError("natural_scrolling must be true or false")

    greeting = profile.get("greeter_greeting")

    if not isinstance(greeting, str) or not greeting.strip():
        raise ValueError("greeter_greeting must be a non-empty string")

    return profile


def generate_header(profile: dict[str, Any]) -> None:
    natural_scrolling = 1 if profile["natural_scrolling"] else 0
    modkey = MODKEYS[profile["modkey"]]
    monitors = profile["monitors"]

    lines = [
        "/*",
        " * ============================================================",
        " * deepBlack Machine Profile",
        " *",
        " * AUTO-GENERATED FILE",
        f" * Machine: {profile['id']}",
        " *",
        " * DO NOT EDIT THIS FILE DIRECTLY.",
        " * ============================================================",
        " */",
        "",
        "#ifndef DEEPBLACK_MACHINE_PROFILE_H",
        "#define DEEPBLACK_MACHINE_PROFILE_H",
        "",
        f'#define DB_MACHINE_ID "{profile["id"]}"',
        f"#define DB_NATURAL_SCROLLING {natural_scrolling}",
        f"#define DB_MODKEY {modkey}",
        "",
        "#define DB_MONITOR_RULES \\",
    ]

    for index, monitor in enumerate(monitors):
        required = {"name", "mfact", "nmaster", "scale"}
        missing = required.difference(monitor)

        if missing:
            raise ValueError(
                "monitor rule is missing: " + ", ".join(sorted(missing))
            )

        name = c_string(monitor["name"])
        mfact = c_float(monitor["mfact"])
        nmaster = int(monitor["nmaster"])
        scale = c_float(monitor["scale"])

        continuation = " \\" if index < len(monitors) - 1 else ""

        lines.append(
            f"    {{ {name}, {mfact}, {nmaster}, {scale}, "
            f"&layouts[0], WL_OUTPUT_TRANSFORM_NORMAL, -1, -1 }},"
            f"{continuation}"
        )

    lines += [
        "",
        "#endif /* DEEPBLACK_MACHINE_PROFILE_H */",
        "",
    ]

    OUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    OUT_HEADER.write_text("\n".join(lines), encoding="utf-8")


def generate_foot_size(profile: dict[str, Any]) -> None:
    OUT_FOOT_SIZE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FOOT_SIZE.write_text(
        f"{profile['foot_font_size']}\n",
        encoding="utf-8",
    )


def generate_greeter(profile: dict[str, Any]) -> None:
    greeting = shlex.quote(profile["greeter_greeting"])

    lines = [
        "#!/bin/sh",
        "set -eu",
        "",
        "# Auto-generated from the selected deepBlack machine profile.",
        f"# Machine: {profile['id']}",
        "# Do not edit by hand.",
        "",
        "exec tuigreet \\",
        f"    --greeting {greeting} \\",
        "    --time \\",
        "    --remember \\",
        "    --remember-session \\",
        "    --asterisks \\",
        "    --user-menu \\",
        "    --cmd /usr/local/bin/deepblack-session \\",
        "    --sessions /usr/share/wayland-sessions \\",
        "    --xsessions /usr/share/xsessions \\",
        "    --theme 'text=white;time=darkgray;container=black;border=cyan;title=cyan;greet=cyan;prompt=blue;input=white;action=darkgray;button=blue'",
        "",
    ]

    OUT_GREETER.parent.mkdir(parents=True, exist_ok=True)
    OUT_GREETER.write_text("\n".join(lines), encoding="utf-8")
    OUT_GREETER.chmod(0o755)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--machine",
        default="generic",
        help="machine profile name from profiles/machines",
    )
    args = parser.parse_args()

    try:
        profile = load_profile(args.machine)
        generate_header(profile)
        generate_foot_size(profile)
        generate_greeter(profile)
    except (FileNotFoundError, ValueError, json.JSONDecodeError) as error:
        parser.error(str(error))

    print(f"[deepBlack] selected machine profile: {profile['id']}")
    print(f"[deepBlack] generated {OUT_HEADER}")
    print(f"[deepBlack] generated {OUT_FOOT_SIZE}")
    print(f"[deepBlack] generated {OUT_GREETER}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
