#!/usr/bin/env python3
"""Generate Neovim Lua color tokens from deepBlack design tokens."""

from __future__ import annotations

import re
import sys
from pathlib import Path

TOKEN_RE = re.compile(
    r"^\s*#define\s+([A-Z][A-Z0-9_]+)\s+"
    r"(0x[0-9A-Fa-f]{6,8}|[A-Z][A-Z0-9_]+)\b"
)


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def find_token_source(root: Path) -> Path | None:
    candidates = [
        root / "generated" / "dwl" / "design_tokens.h",
        root / "source" / "dwl" / "design_tokens.h",
    ]

    for candidate in candidates:
        if candidate.exists():
            return candidate

    return None


def resolve_token(
    name: str,
    raw_tokens: dict[str, str],
) -> str:
    if name not in raw_tokens:
        raise ValueError(f"unknown token: {name}")

    value = raw_tokens[name]
    seen = {name}

    while value in raw_tokens:
        if value in seen:
            chain = " -> ".join([*seen, value])
            raise ValueError(f"circular token alias: {chain}")

        seen.add(value)
        value = raw_tokens[value]

    if not value.lower().startswith("0x"):
        raise ValueError(f"{name} does not resolve to a hexadecimal value")

    return value


def hex_to_rgb(value: str) -> str:
    raw = value.removeprefix("0x").removeprefix("0X")

    if len(raw) == 8:
        raw = raw[:6]

    if len(raw) != 6:
        raise ValueError(f"unsupported color token value: {value}")

    return f"#{raw.lower()}"


def main() -> int:
    root = repo_root()
    source = find_token_source(root)
    target = (
        root
        / "generated"
        / "nvim"
        / "lua"
        / "deepblack"
        / "tokens.lua"
    )

    if source is None:
        print("missing generated design token header", file=sys.stderr)
        return 1

    raw_tokens: dict[str, str] = {}

    for line in source.read_text(encoding="utf-8").splitlines():
        match = TOKEN_RE.match(line)

        if match:
            name, value = match.groups()
            raw_tokens[name] = value

    if not raw_tokens:
        print(f"no color tokens found in {source}", file=sys.stderr)
        return 1

    resolved_tokens: dict[str, str] = {}

    try:
        for name in raw_tokens:
            resolved_tokens[name] = hex_to_rgb(
                resolve_token(name, raw_tokens)
            )
    except ValueError as error:
        print(f"token resolution failed: {error}", file=sys.stderr)
        return 1

    target.parent.mkdir(parents=True, exist_ok=True)

    with target.open("w", encoding="utf-8") as file:
        file.write("-- GENERATED FILE — DO NOT EDIT BY HAND\n")
        file.write(
            "-- Source: "
            + str(source.relative_to(root))
            + "\n"
        )
        file.write(
            "-- Generated by: tools/generate-nvim-tokens.py\n\n"
        )
        file.write("return {\n")

        for name in sorted(resolved_tokens):
            file.write(
                f'  {name} = "{resolved_tokens[name]}",\n'
            )

        file.write("}\n")

    print(
        f"generated {target.relative_to(root)} "
        f"from {source.relative_to(root)}"
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
