#!/usr/bin/env python3
"""Generate deepBlack theme assets from a selected flavor profile."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
FLAVORS_DIR = ROOT / "profiles" / "flavors"

OUT_DWL = ROOT / "generated" / "dwl" / "design_tokens.h"
OUT_FOOT = ROOT / "generated" / "foot" / "foot.ini"
OUT_WMENU = ROOT / "generated" / "wmenu" / "deepblack-wmenu"

REQUIRED_TOKENS = {
    "SURFACE_00",
    "SURFACE_01",
    "SURFACE_02",
    "SURFACE_03",
    "SURFACE_04",
    "TEXT_PRIMARY",
    "TEXT_SECONDARY",
    "TEXT_MUTED",
    "ACCENT_PRIMARY",
    "ACCENT_SECONDARY",
    "ACCENT_DIAGNOSTIC",
    "STATE_SUCCESS",
    "STATE_WARNING",
    "STATE_CRITICAL",
    "BORDER_INACTIVE",
    "BORDER_ACTIVE",
    "BORDER_CRITICAL",
    "SYNTAX_COMMENT",
    "SYNTAX_KEYWORD",
    "SYNTAX_FUNCTION",
    "SYNTAX_STRING",
    "SYNTAX_NUMBER",
    "SYNTAX_TYPE",
    "SYNTAX_CONSTANT",
    "SYNTAX_OPERATOR",
    "SYNTAX_SPECIAL",
    "SYNTAX_VARIABLE",
    "SYNTAX_PROPERTY",
    "SYNTAX_PARAMETER",
    "SYNTAX_PREPROC",
}

GROUPS = {
    "SURFACE": "Surface Tokens",
    "TEXT": "Text Tokens",
    "ACCENT": "Accent Tokens",
    "STATE": "State Tokens",
    "BORDER": "Border Tokens",
    "SYNTAX": "Syntax Tokens",
}


def group_for(name: str) -> str:
    return name.split("_", 1)[0]


def load_flavor(flavor: str) -> tuple[Path, dict[str, str]]:
    path = FLAVORS_DIR / f"{flavor}.json"

    if not path.is_file():
        available = ", ".join(
            sorted(profile.stem for profile in FLAVORS_DIR.glob("*.json"))
        )
        raise FileNotFoundError(
            f"unknown flavor profile: {flavor}\n"
            f"available flavors: {available or 'none'}"
        )

    profile: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))

    if profile.get("id") != flavor:
        raise ValueError(
            f"profile id {profile.get('id')!r} does not match filename {flavor!r}"
        )

    tokens = profile.get("tokens")

    if not isinstance(tokens, dict):
        raise ValueError("flavor profile must contain a tokens object")

    missing = REQUIRED_TOKENS.difference(tokens)

    if missing:
        raise ValueError(
            "flavor profile is missing required tokens: "
            + ", ".join(sorted(missing))
        )

    for name, value in tokens.items():
        if not isinstance(name, str) or not isinstance(value, str):
            raise ValueError("token names and values must be strings")

    foot = profile.get("foot", {})
    if not isinstance(foot, dict):
        raise ValueError("flavor foot settings must be an object")

    alpha = foot.get("alpha", 1.0)
    alpha_mode = foot.get("alpha_mode", "default")

    if isinstance(alpha, bool) or not isinstance(alpha, (int, float)):
        raise ValueError("foot alpha must be a number")

    if not 0.0 <= float(alpha) <= 1.0:
        raise ValueError("foot alpha must be between 0.0 and 1.0")

    if alpha_mode not in {"default", "matching", "all"}:
        raise ValueError(
            "foot alpha_mode must be default, matching, or all"
        )

    foot_settings = {
        "alpha": float(alpha),
        "alpha_mode": alpha_mode,
    }

    return path, tokens, foot_settings


def resolve_token(tokens: dict[str, str], value: str) -> str:
    """Resolve aliases such as BORDER_ACTIVE -> ACCENT_PRIMARY -> hex."""

    seen: set[str] = set()

    while value in tokens:
        if value in seen:
            raise ValueError(f"circular token reference detected: {value}")

        seen.add(value)
        value = tokens[value]

    return value


def c_to_hex(tokens: dict[str, str], name: str) -> str:
    """Convert 0xRRGGBBAA into Foot's RRGGBB format."""

    value = resolve_token(tokens, tokens[name])

    if not value.startswith("0x") or len(value) != 10:
        raise ValueError(
            f"{name} does not resolve to a 0xRRGGBBAA value: {value}"
        )

    return value[2:8]


def generate_dwl(
    tokens: dict[str, str],
    source: Path,
    flavor: str,
) -> None:
    source_name = source.relative_to(ROOT)

    lines = [
        "/*",
        " * ============================================================",
        " * deepBlack Design Tokens",
        " *",
        " * AUTO-GENERATED FILE",
        f" * Flavor: {flavor}",
        f" * Source: {source_name}",
        " *",
        " * DO NOT EDIT THIS FILE DIRECTLY.",
        " * ============================================================",
        " */",
        "",
        "#ifndef DESIGN_TOKENS_H",
        "#define DESIGN_TOKENS_H",
        "",
    ]

    current_group = None

    for name, value in tokens.items():
        group = group_for(name)

        if group != current_group:
            if current_group is not None:
                lines.append("")

            lines.append(
                f"/* {GROUPS.get(group, group.title() + ' Tokens')} */"
            )
            current_group = group

        lines.append(f"#define {name:<20} {value}")

    lines += [
        "",
        "#endif /* DESIGN_TOKENS_H */",
        "",
    ]

    OUT_DWL.parent.mkdir(parents=True, exist_ok=True)
    OUT_DWL.write_text("\n".join(lines), encoding="utf-8")

    print(f"[deepBlack] generated {OUT_DWL}")


def generate_foot(
    tokens: dict[str, str],
    source: Path,
    flavor: str,
    foot_font_size: int,
    foot_settings: dict[str, Any],
) -> None:
    source_name = source.relative_to(ROOT)

    lines = [
        f"# Auto-generated from {source_name}",
        f"# Flavor: {flavor}",
        "# Do not edit by hand.",
        "",
        "[main]",
        f"font=JetBrainsMono Nerd Font Mono:size={foot_font_size}",
        "pad=8x8",
        "",
        "[colors-dark]",
        f"alpha={foot_settings['alpha']:.2f}",
        f"alpha-mode={foot_settings['alpha_mode']}",
        f"foreground={c_to_hex(tokens, 'TEXT_PRIMARY')}",
        f"background={c_to_hex(tokens, 'SURFACE_00')}",
        "",
        f"regular0={c_to_hex(tokens, 'SURFACE_00')}",
        f"regular1={c_to_hex(tokens, 'STATE_CRITICAL')}",
        f"regular2={c_to_hex(tokens, 'ACCENT_PRIMARY')}",
        f"regular3={c_to_hex(tokens, 'STATE_WARNING')}",
        f"regular4={c_to_hex(tokens, 'ACCENT_SECONDARY')}",
        f"regular5={c_to_hex(tokens, 'TEXT_SECONDARY')}",
        f"regular6={c_to_hex(tokens, 'ACCENT_DIAGNOSTIC')}",
        f"regular7={c_to_hex(tokens, 'TEXT_PRIMARY')}",
        "",
        f"bright0={c_to_hex(tokens, 'TEXT_MUTED')}",
        f"bright1={c_to_hex(tokens, 'STATE_CRITICAL')}",
        f"bright2={c_to_hex(tokens, 'ACCENT_PRIMARY')}",
        f"bright3={c_to_hex(tokens, 'STATE_WARNING')}",
        f"bright4={c_to_hex(tokens, 'ACCENT_SECONDARY')}",
        f"bright5={c_to_hex(tokens, 'TEXT_SECONDARY')}",
        f"bright6={c_to_hex(tokens, 'ACCENT_DIAGNOSTIC')}",
        f"bright7={c_to_hex(tokens, 'TEXT_PRIMARY')}",
        "",
        f"selection-foreground={c_to_hex(tokens, 'SURFACE_00')}",
        f"selection-background={c_to_hex(tokens, 'ACCENT_PRIMARY')}",
        f"cursor={c_to_hex(tokens, 'SURFACE_00')} "
        f"{c_to_hex(tokens, 'TEXT_SECONDARY')}",
        "",
    ]

    OUT_FOOT.parent.mkdir(parents=True, exist_ok=True)
    OUT_FOOT.write_text("\n".join(lines), encoding="utf-8")

    print(f"[deepBlack] generated {OUT_FOOT}")



def generate_wmenu(
    tokens: dict[str, str],
    source: Path,
    flavor: str,
) -> None:
    source_name = source.relative_to(ROOT)

    lines = [
        "#!/usr/bin/env sh",
        f"# Auto-generated from {source_name}",
        f"# Flavor: {flavor}",
        "# Do not edit by hand.",
        "",
        "exec wmenu-run \\",
        '  -f "JetBrainsMono Nerd Font 12" \\',
        f'  -n "{c_to_hex(tokens, "TEXT_PRIMARY")}" \\',
        f'  -N "{c_to_hex(tokens, "SURFACE_00")}" \\',
        f'  -m "{c_to_hex(tokens, "ACCENT_PRIMARY")}" \\',
        f'  -M "{c_to_hex(tokens, "SURFACE_01")}" \\',
        f'  -s "{c_to_hex(tokens, "SURFACE_00")}" \\',
        f'  -S "{c_to_hex(tokens, "ACCENT_PRIMARY")}" \\',
        '  "$@"',
        "",
    ]

    OUT_WMENU.parent.mkdir(parents=True, exist_ok=True)
    OUT_WMENU.write_text("\n".join(lines), encoding="utf-8")
    OUT_WMENU.chmod(0o755)

    print(f"[deepBlack] generated {OUT_WMENU}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--flavor",
        default="deepblack",
        help="flavor profile name from profiles/flavors",
    )
    args = parser.parse_args()

    try:
        source, tokens, foot_settings = load_flavor(args.flavor)

        foot_font_size = int(
            os.environ.get("DEEPBLACK_FOOT_FONT_SIZE", "12")
        )

        if not 6 <= foot_font_size <= 32:
            raise ValueError(
                "DEEPBLACK_FOOT_FONT_SIZE must be between 6 and 32"
            )

        generate_dwl(tokens, source, args.flavor)
        generate_foot(
            tokens,
            source,
            args.flavor,
            foot_font_size,
            foot_settings,
        )
        generate_wmenu(tokens, source, args.flavor)
    except (
        FileNotFoundError,
        ValueError,
        json.JSONDecodeError,
    ) as error:
        parser.error(str(error))

    print(f"[deepBlack] selected flavor profile: {args.flavor}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
