#!/usr/bin/env python3
"""Generate Neovim Lua color tokens from deepBlack design token headers.

This writes generated/nvim/lua/deepblack/tokens.lua.

Do not edit the generated Lua file by hand.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

TOKEN_RE = re.compile(
    r"^\s*#define\s+([A-Z][A-Z0-9_]+)\s+(0x[0-9A-Fa-f]{6,8})\b"
)


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def hex_to_rgb(value: str) -> str:
    raw = value.removeprefix("0x").removeprefix("0X")

    # Accept 0xRRGGBBAA, but Neovim highlight groups use #RRGGBB.
    if len(raw) == 8:
        raw = raw[:6]

    if len(raw) != 6:
        raise ValueError(f"unsupported color token value: {value}")

    return f"#{raw.lower()}"


def find_token_source(root: Path) -> Path | None:
    candidates = [
        root / "header" / "design_tokens.h",
        root / "generated" / "dwl" / "design_tokens.h",
        root / "source" / "dwl" / "design_tokens.h",
    ]

    for candidate in candidates:
        if candidate.exists():
            return candidate

    return None


def main() -> int:
    root = repo_root()
    source = find_token_source(root)
    target = root / "generated" / "nvim" / "lua" / "deepblack" / "tokens.lua"

    if source is None:
        print("missing token source; searched:", file=sys.stderr)
        print("  header/design_tokens.h", file=sys.stderr)
        print("  generated/dwl/design_tokens.h", file=sys.stderr)
        print("  source/dwl/design_tokens.h", file=sys.stderr)
        return 1

    tokens: dict[str, str] = {}

    for line in source.read_text(encoding="utf-8").splitlines():
        match = TOKEN_RE.match(line)
        if not match:
            continue

        name, value = match.groups()
        tokens[name] = hex_to_rgb(value)

    if not tokens:
        print(f"no color tokens found in {source}", file=sys.stderr)
        return 1

    target.parent.mkdir(parents=True, exist_ok=True)

    with target.open("w", encoding="utf-8") as f:
        f.write("-- GENERATED FILE — DO NOT EDIT BY HAND\n")
        f.write("-- Source: " + str(source.relative_to(root)) + "\n")
        f.write("-- Generated by: tools/generate-nvim-tokens.py\n\n")
        f.write("return {\n")

        for name in sorted(tokens):
            f.write(f'  {name} = "{tokens[name]}",\n')

        f.write("}\n")

    print(f"generated {target.relative_to(root)} from {source.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
